version: 1.2
workflows:
  - name: hello_world
    subclass: WDL
    primaryDescriptorPath: /hello_world.wdl
  - name: count_seq_ns
    subclass: WDL
    primaryDescriptorPath: /count_seq_ns.wdl
  - name: count_seq_ns_parallel
    subclass: WDL
    primaryDescriptorPath: /count_seq_ns_parallel.wdl
  - name: bed2bb
    subclass: WDL
    primaryDescriptorPath: /bed2bb.wdl
